version: '3.9'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm_popurri_container
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
